package com.example.habitforge.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Habit - Entity model representing a user's habit in the database
 *
 * This data class defines the structure for storing habit information in the Room database.
 * Each habit tracks its completion status, consecutive day streak, and last completion date
 * to encourage consistent daily practice.
 *
 * Database Table: "habits"
 * Primary Key: Auto-generated integer ID
 *
 * @property id Unique identifier for the habit (auto-generated by Room)
 * @property title Name of the habit (e.g., "Morning Exercise", "Read for 20 minutes")
 * @property description Optional details about the habit (e.g., "30 min cardio workout")
 * @property isCompleted Whether the habit was completed today (resets daily in logic)
 * @property streak Number of consecutive days the habit has been completed
 *                  - Increments when completed on consecutive days
 *                  - Resets to 1 if there's a gap in completion
 *                  - Remains 0 for new habits that haven't been completed yet
 * @property lastCompletedDate ISO date string of the last completion (e.g., "2026-01-01")
 *                             - Used to calculate streak continuity
 *                             - Null for habits that have never been completed
 *
 * Example:
 * ```
 * val habit = Habit(
 *     id = 1,
 *     title = "Meditation",
 *     description = "10 minutes mindfulness",
 *     isCompleted = true,
 *     streak = 7,
 *     lastCompletedDate = "2026-01-01"
 * )
 * ```
 */
@Entity(tableName = "habits")
data class Habit(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val description: String,
    val isCompleted: Boolean = false,
    val streak: Int = 0,
    val lastCompletedDate: String? = null
)
